# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'photo-share' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftProtobuf', '~> 0.9.903'
  pod 'RealmSwift', '~> 2.8.2'
  pod 'SnapKit', '~> 3.2.0'

  # Pods for photo-share

  target 'photo-shareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
