# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "SharedCollection" do
    optional :id, :string, 1
    optional :creation_timestamp, :int32, 2
    optional :assets, :message, 3, "Assets"
  end
  add_message "Assets" do
    repeated :assets, :message, 1, "Asset"
  end
  add_message "Asset" do
    optional :id, :string, 1
    optional :checksum, :string, 2
  end
end

SharedCollection = Google::Protobuf::DescriptorPool.generated_pool.lookup("SharedCollection").msgclass
Assets = Google::Protobuf::DescriptorPool.generated_pool.lookup("Assets").msgclass
Asset = Google::Protobuf::DescriptorPool.generated_pool.lookup("Asset").msgclass
